# Catppuccin Frappé
font=CaskaydiaCove Nerd Font:size=12
dpi-aware=yes
prompt="❯ "
icon-theme=Adwaita
terminal=ghostty
layer=overlay
lines=12
width=40
horizontal-pad=20
vertical-pad=14
inner-pad=8

[colors]
background=303446ee
text=c6d0f5ff
match=8caaeeff
selection=51576dff
selection-text=c6d0f5ff
selection-match=8caaeeff
border=8caaeeff

[border]
width=2
radius=12
