# Catppuccin Frappé
general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 2
    no_fade_in = false
}

background {
    monitor =
    path = ~/.config/hypr/wallpapers/frappe-base.png
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 280, 50
    position = 0, -120
    halign = center
    valign = center
    outline_thickness = 2
    inner_color = rgba(48, 52, 70, 0.85)        # base
    outer_color = rgba(140, 170, 238, 0.9)      # blue
    font_color = rgb(198, 208, 245)             # text
    placeholder_text = <i>Password…</i>
    fade_on_empty = true
    rounding = 12
    check_color = rgb(166, 209, 137)            # green
    fail_color = rgb(231, 130, 132)             # red
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 90
    font_family = CaskaydiaCove Nerd Font Bold
    color = rgb(198, 208, 245)
    position = 0, 200
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B %Y')"
    font_size = 18
    font_family = CaskaydiaCove Nerd Font
    color = rgb(181, 191, 226)                  # subtext1
    position = 0, 100
    halign = center
    valign = center
}

# User
label {
    monitor =
    text =   $USER
    font_size = 14
    font_family = CaskaydiaCove Nerd Font
    color = rgb(181, 191, 226)
    position = 0, -60
    halign = center
    valign = center
}
